# Generated by Django 5.0.6 on 2024-07-30 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tariff_type",
                    models.CharField(
                        choices=[
                            ("1", "FREE"),
                            ("2", "BASIC"),
                            ("3", "PRO"),
                            ("4", "ADVANCED"),
                            ("5", "ENTERPRISE"),
                        ],
                        max_length=1,
                    ),
                ),
                ("price", models.IntegerField()),
                ("number_of_unique_students_allowed", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("product", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("expires", models.DateTimeField()),
                ("type", models.CharField(max_length=255)),
                ("renewal", models.BooleanField(default=False)),
                ("rebill_id", models.CharField(max_length=255)),
                ("email_sent", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
