# Generated by Django 5.0.6 on 2024-07-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="number_of_unique_students_allowed",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="plan",
            name="tariff_type",
            field=models.CharField(
                choices=[
                    ("0", "FREE"),
                    ("1", "BASIC"),
                    ("2", "PRO"),
                    ("3", "ADVANCED"),
                    ("4", "ENTERPRISE"),
                ],
                max_length=1,
            ),
        ),
    ]
