# Generated by Django 5.0.6 on 2024-07-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_plan_number_of_unique_students_allowed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="id",
        ),
        migrations.AlterField(
            model_name="plan",
            name="tariff_type",
            field=models.CharField(
                choices=[
                    ("0", "FREE"),
                    ("1", "BASIC"),
                    ("2", "PRO"),
                    ("3", "ADVANCED"),
                    ("4", "ENTERPRISE"),
                ],
                max_length=1,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
