# Generated by Django 5.0.6 on 2024-07-30 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_remove_plan_id_alter_plan_tariff_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="plan",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="payments.plan",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="plan",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to="payments.plan",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plan",
            name="number_of_unique_students_allowed",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plan",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
