# Generated by Django 5.0.6 on 2024-07-30 09:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_order_plan_subscription_plan_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
    ]
