# Generated by Django 5.0.6 on 2024-07-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0005_remove_order_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="email_sent",
        ),
        migrations.AddField(
            model_name="subscription",
            name="email_warning_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
