# Generated by Django 5.0.6 on 2024-08-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0006_remove_subscription_email_sent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="for_whom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
