# Generated by Django 5.0.6 on 2024-08-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0007_plan_for_whom_plan_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="type",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="rebill_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
