# Generated by Django 5.0.6 on 2024-08-07 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "payments",
            "0008_remove_subscription_type_alter_subscription_expires_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="tariff_type",
            field=models.CharField(
                choices=[
                    ("1", "BASIC"),
                    ("2", "PRO"),
                    ("3", "ADVANCED"),
                    ("4", "ENTERPRISE"),
                ],
                max_length=1,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 6, 10, 40, 34, 652233, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="renewal",
            field=models.BooleanField(default=True),
        ),
    ]
