# Generated by Django 5.0.6 on 2024-08-08 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0009_alter_plan_tariff_type_alter_subscription_expires_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="expires",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 9, 7, 9, 2, 28, 84552, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
