# Generated by Django 5.0.6 on 2024-08-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0010_alter_order_order_id_alter_subscription_expires"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="expires",
            field=models.DateTimeField(),
        ),
    ]
