# Generated by Django 5.0.6 on 2024-08-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0011_alter_subscription_expires"),
    ]

    operations = [
        migrations.CreateModel(
            name="DebugMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
            ],
        ),
    ]
