# Generated by Django 5.0.6 on 2024-08-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0012_debugmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="NEW"),
        ),
    ]
