# Generated by Django 5.0.6 on 2024-08-14 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0013_order_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"ordering": ["-expires"]},
        ),
    ]
