# Generated by Django 5.0.6 on 2024-07-23 14:04

import django.utils.timezone
import users.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="created",
            field=users.models.AutoDateTimeField(default=django.utils.timezone.now),
        ),
    ]
