# Generated by Django 5.0.6 on 2024-07-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_course_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_active_link",
            field=models.BooleanField(default=True),
        ),
    ]
