# Generated by Django 5.0.6 on 2024-08-01 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_course_is_active_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="anon_name",
        ),
    ]
