# Generated by Django 5.0.6 on 2024-08-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["code"], name="users_cours_code_e070e0_idx"),
        ),
    ]
