# Generated by Django 5.0.6 on 2024-08-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_course_users_cours_code_e070e0_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("PB", "PUBLISHED"), ("AR", "ARCHIVED")],
                default="PB",
                max_length=2,
            ),
        ),
    ]
