# Generated by Django 5.0.6 on 2024-08-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_course_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
