# Generated by Django 5.0.6 on 2024-07-15 08:46

import discussionboard.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created', discussionboard.models.AutoDateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntermediateCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='question', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('id_within_course', models.IntegerField()),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_answered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['question'],
            },
        ),
        migrations.CreateModel(
            name='Viewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
            options={
                'ordering': ['to_date'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('intermediatepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discussionboard.intermediatepost')),
            ],
            options={
                'ordering': ['created'],
            },
            bases=('discussionboard.intermediatepost',),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('intermediatepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discussionboard.intermediatepost')),
            ],
            options={
                'abstract': False,
            },
            bases=('discussionboard.intermediatepost',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('intermediatepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='discussionboard.intermediatepost')),
            ],
            options={
                'ordering': ['-created'],
            },
            bases=('discussionboard.intermediatepost',),
        ),
    ]
