# Generated by Django 5.0.6 on 2024-07-21 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discussionboard", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["-created"]},
        ),
    ]
