# Generated by Django 5.0.6 on 2024-07-23 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discussionboard", "0003_alter_answer_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intermediatecategory",
            name="slug",
        ),
    ]
