# Generated by Django 5.0.6 on 2024-07-23 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discussionboard", "0004_remove_intermediatecategory_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="intermediatecategory",
            name="course",
        ),
    ]
