# Generated by Django 5.0.6 on 2024-07-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discussionboard", "0005_remove_intermediatecategory_course"),
        ("users", "0002_course_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="users.course",
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="users.course",
            ),
        ),
    ]
