# Generated by Django 5.0.6 on 2024-07-23 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discussionboard", "0006_category_course_subcategory_course"),
        ("users", "0002_course_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="course",
            field=models.ForeignKey(
                default=18,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categories",
                to="users.course",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="course",
            field=models.ForeignKey(
                default=18,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategories",
                to="users.course",
            ),
            preserve_default=False,
        ),
    ]
