# Generated by Django 5.0.6 on 2024-07-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discussionboard", "0007_alter_category_course_alter_subcategory_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="intermediatepost",
            name="is_posted_by_admin",
            field=models.BooleanField(default=False),
        ),
    ]
