# Generated by Django 5.0.6 on 2024-07-28 15:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discussionboard", "0008_intermediatepost_is_posted_by_admin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={"ordering": ["-is_posted_by_admin", "-created"]},
        ),
    ]
