# Generated by Django 5.0.6 on 2024-08-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discussionboard", "0012_alter_intermediatepost_author"),
        ("users", "0006_alter_user_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="week",
            index=models.Index(
                fields=["course"], name="discussionb_course__83059b_idx"
            ),
        ),
    ]
