# Generated by Django 5.0.6 on 2024-08-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discussionboard", "0013_week_discussionb_course__83059b_idx"),
        ("users", "0006_alter_user_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(fields=["week"], name="discussionb_week_id_6537a6_idx"),
        ),
    ]
