# Generated by Django 5.0.6 on 2024-08-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discussionboard", "0014_thread_discussionb_week_id_6537a6_idx"),
        ("users", "0007_course_users_cours_code_e070e0_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="thread",
            name="discussionb_week_id_6537a6_idx",
        ),
        migrations.AddIndex(
            model_name="thread",
            index=models.Index(
                fields=["week", "course"], name="discussionb_week_id_4c6b88_idx"
            ),
        ),
    ]
