# Generated by Django 5.0.6 on 2024-08-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discussionboard", "0016_alter_intermediatepost_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thread",
            name="views",
            field=models.ManyToManyField(blank=True, to="discussionboard.viewer"),
        ),
    ]
