# Generated by Django 5.0.6 on 2024-07-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discussionboard", "__first__"),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="user",
            new_name="users",
        ),
        migrations.AddField(
            model_name="notification",
            name="threads",
            field=models.ManyToManyField(
                related_name="notifications", to="discussionboard.thread"
            ),
        ),
    ]
