# Generated by Django 5.0.6 on 2024-07-29 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discussionboard", "__first__"),
        ("notifications", "0002_rename_user_notification_users_notification_threads"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="threads",
        ),
        migrations.AddField(
            model_name="notification",
            name="thread",
            field=models.ForeignKey(
                default=189,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="discussionboard.thread",
            ),
            preserve_default=False,
        ),
    ]
