# Generated by Django 5.0.6 on 2024-08-18 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "discussionboard",
            "0015_remove_thread_discussionb_week_id_6537a6_idx_and_more",
        ),
        ("notifications", "0004_remove_notification_users_notification_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="author_name",
            field=models.CharField(default="Andrew", max_length=255),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "thread"], name="notificatio_user_id_121108_idx"
            ),
        ),
    ]
