# Generated by Django 5.0.6 on 2024-08-21 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_notification_author_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="author_name",
        ),
    ]
